language: node_js
node_js:
  - "4"
  - "5"
  - "0.12"
  - "0.10"
  - "0.8"
install:
  - npm install
  - npm install typescript typings
  - ./node_modules/.bin/typings install
  - ./node_modules/.bin/tsc -p .